name: "Pull Request Labeler"

on:
  workflow_dispatch:
  pull_request:
  pull_request_review:
    types:
      - submitted

permissions:
  contents: read
  pull-requests: write

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const labels = github.rest.issues.listLabelsOnIssue({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            })
            console.log(labels)

  label-changes-requested:
    if: github.event.review.state == 'changes_requested'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v6
        with:
          script: console.log(context)

            # github.rest.issues.addLabels({
            #   issue_number: context.issue.number,
            #   owner: context.repo.owner,
            #   repo: context.repo.repo,
            #   labels: ['changes-requested']
            # })
      - uses: actions/github-script@v6
        with:
          script: console.log(context.repo)
      - uses: actions/github-script@v6
        with:
          script: console.log(context.repo.owner)
      - uses: actions/github-script@v6
        with:
          script: console.log(context.repo.repo)