name: "Pull Request Labeler"

on:
  pull_request:
  pull_request_review:
    types:
      - submitted

permissions:
  contents: read
  pull-requests: write

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

  label-changes-requested:
    if: github.event.review.state == 'changes_requested'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v6
        with:
          script: console.log(context)

            # github.rest.issues.addLabels({
            #   issue_number: context.issue.number,
            #   owner: context.repo.owner,
            #   repo: context.repo.repo,
            #   labels: ['changes-requested']
            # })
      - uses: actions/github-script@v6
        with:
          script: console.log(context.repo)
      - uses: actions/github-script@v6
        with:
          script: console.log(context.repo.owner)
      - uses: actions/github-script@v6
        with:
          script: console.log(context.repo.repo)