on:
  pull_request:
    types:
      - opened
      - review_requested  
      - closed
  pull_request_review:
    types:
      - submitted

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

  # apply-label:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/github-script@v6
  #       with:
  #         script: |
  #           github.rest.issues.addLabels({
  #             issue_number: context.issue.number,
  #             owner: context.repository.owner,
  #             repo: context.repository.repo,
  #             labels: ['changes-requested']
  #           })
