name: Build and Test

on: 
  workflow_dispatch:
  
  pull_request:
    types: [reopened, ready_for_review, closed, review_requested]

  push:
    branches:
      - 'master'
      - 'releases/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Code Checkout
      uses: actions/checkout@v3

    - name: Setup .NET 7
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x